Repository see-k/projectLasagna, pull requests merged in 2021-05, with the labels that each got.

#21 Chike branch
  miscellanous/img/SCHEMA.JPG
  miscellanous/img/UML CHART.JPG
  miscellanous/img/add_sighting_form.png
  miscellanous/img/cat_profiles_w_edit.png
  miscellanous/img/flowChart.JPG
  miscellanous/img/other_login.png
  miscellanous/img/vXJrdYADVqBveqVJ4n672K.jpg
  miscellanous/img/view-sightings.png
  react/test_file.txt
Labels: documentation

#88 Updated Delete
  cat-tracker/src/main/java/learn/cat/data/UsersJdbcTemplateRepository.java
  cat-tracker/src/test/java/learn/cat/data/UsersJdbcTemplateRepositoryTest.java
Labels: bug, help wanted

#92 Quinn branch
  cat-tracker/src/main/java/learn/cat/data/ReportJdbcTemplateRepository.java
  cat-tracker/src/main/java/learn/cat/data/SightingJdbcTemplateRepository.java
  cat-tracker/src/main/java/learn/cat/data/SightingRepository.java
  cat-tracker/src/main/java/learn/cat/data/mappers/SightingMapper.java
  cat-tracker/src/main/java/learn/cat/models/Cat.java
  cat-tracker/src/main/java/learn/cat/models/Sighting.java
  cat-tracker/src/test/java/learn/cat/data/ReportJdbcTemplateRepositoryTest.java
  cat-tracker/src/test/java/learn/cat/data/SightingJdbcTemplateRepositoryTest.java
  database/cat-tracker-schema-prod.sql
  database/cat-tracker-schema-test.sql
Labels: enhancement

#112 Users and Locations controllers ,services, service test, HTTP tests. Error and Validation handling
  README.md
  cat-tracker/http/location.http
  cat-tracker/http/users.http
  cat-tracker/src/main/java/learn/cat/controllers/ErrorResponse.java
  cat-tracker/src/main/java/learn/cat/controllers/LocationController.java
  cat-tracker/src/main/java/learn/cat/controllers/UsersController.java
  cat-tracker/src/main/java/learn/cat/data/UsersJdbcTemplateRepository.java
  cat-tracker/src/main/java/learn/cat/domain/LocationService.java
  cat-tracker/src/main/java/learn/cat/domain/UsersService.java
  cat-tracker/src/main/java/learn/cat/models/Location.java
  cat-tracker/src/main/java/learn/cat/models/Users.java
  cat-tracker/src/test/java/learn/cat/domain/LocationServiceTest.java
  cat-tracker/src/test/java/learn/cat/domain/UsersServiceTest.java
Labels: bug, help wanted

#116 working delete in usersjdbc
  cat-tracker/http/users.http
  cat-tracker/src/main/java/learn/cat/data/UsersJdbcTemplateRepository.java
  cat-tracker/src/main/java/learn/cat/data/UsersRepository.java
  cat-tracker/src/test/java/learn/cat/data/SightingJdbcTemplateRepositoryTest.java
Labels: wontfix

#124 react app project tree updated
  Google_API_key.txt
  cat-tracker-react/.env.development
  cat-tracker-react/.env.production
  cat-tracker-react/package-lock.json
  cat-tracker-react/package.json
  cat-tracker-react/src/App.css
  cat-tracker-react/src/App.js
  cat-tracker-react/src/components/AddCat.js
  cat-tracker-react/src/components/AddSighting.js
  cat-tracker-react/src/components/CatProfile.js
  cat-tracker-react/src/components/Home.js
  cat-tracker-react/src/components/Nav.js
  cat-tracker-react/src/components/Sighting.js
  cat-tracker-react/src/components/UpdateCat.js
  cat-tracker-react/src/components/UpdateSighting.js
  cat-tracker-react/src/components/ViewCats.js
  cat-tracker-react/src/components/ViewSightings.js
  cat-tracker-react/src/static/About.js
  cat-tracker-react/src/static/Contact.js
  cat-tracker-react/src/static/FAQ.js
  cat-tracker-react/src/static/NotFound.js
  package-lock.json
Labels: enhancement
